### PR TITLE
[RDY] Update UML

### PR DESCRIPTION
**Pull request by Hjdskes**
This solves #72 and #59.

### CODE REVIEW

**Comment by Hjdskes** [comment]
I just noticed that this renders some images differently, for example, the arrows in the `returns` and `executes` lines in `uml-commands` are not rendered in the new image. The same goes for the `uml-func-comp` :|

**Comment by gfokkema** [comment]
`inkscape t.svg --export-pdf=t.pdf`

fixes the rendering issues.

**Comment by Hjdskes** [comment]
I have rebased this branch on #86, exported all .uxf files as .svg files and converted those to .pdf. I believe everything now renders correctly, except
1. Figure 2.1, it's too wide. Scaling the width should resolve this;
2. Figure 5.3, "uses" is cut off. Minor issue but perhaps worth investigating regardless.

Please do compile and take a look yourselves!

**Comment by Balletie** [comment]
Other updates will be in later PRs

**Pull request merged**
